# Kryptonite

I took a walk around the world to ease my troubled mind  
I left my body lying somewhere in the sands of time  
I watched the world float to the dark side of the moon  
And I feel there is nothing I can do, oh yeah  
I watched the world float to the dark side of the moon  
After all I knew it had to be something to do with you  
I really don't mind what happens now and then  
As long as you'll be my friend at the end  
If I go crazy then will you still call me Superman?  
If I'm alive and well, will you be there a holding my hand?  
I'll keep you by my side with my superhuman might  
Kryptonite  
No no no no no no no  
You called me strong, you called me weak, but still your secrets I will keep  
You took for granted all the times I never let you down  
You stumbled in and bumped your head, if not for me then you'd be dead  
I picked you up and put you back on solid ground  
If I go crazy then will you still call me Superman?  
If I'm alive and well, will you be there a holding my hand?  
I'll keep you by my side with my superhuman might  
Kryptonite  
No no no no no no no, no no no no no no no  
If I go crazy then will you still call me Superman?  
If I'm alive and well, will you be there a holding my hand?  
I'll keep you by my side with my superhuman might  
Kryptonite  
Yeah!  
If I go crazy then will you still call me Superman?  
If I'm alive and well, will you be there a holding my hand?  
I'll keep you by my side with my superhuman might  
Kryptonite  
No no no no no no no  
Ho, woh, woh  
Ho, woh, woh  
Ho, woh, woh
