# Play-That-Funky-Music

Hey... do it now  
Yeah hey  
Hey once I was a boogie singer playin' in a rock and roll band  
I never had no problems yeah burnin' down one night stands  
And everything around me yeah  
Got to stop to feelin' so low  
And I decided quickly yes I did  
To disco down and check out the show  
Yeah they was dancin' and singin' and movin' to the groovin'  
And just when it hit me somebody turned around and shouted  
Play that funky music white boy  
Play that funky music right  
Play that funky music white boy  
Lay down the boogie and play that funky music till you die  
Hee-hee  
Till you die (yeah)  
Yeah-yeah  
Well I tried to understand this (yeah) hey  
I thought that they were out of their minds huh  
How could I be so foolish?  
How could I?  
To not see I was be one behind  
So still I kept on fighting  
Well losin' every step of the way  
(what you do?)  
I said I must go back there I got to go back  
And check to see if things still the same  
Yeah they was dancin' and singin' and movin' to the groovin'  
And just when it hit me somebody turned around and shouted  
Play that funky music white boy  
Play that funky music right  
Play that funky music white boy  
Lay down the boogie and play that funky music till you die hey  
Till you die (yeah)  
Oh till you die  
Come on play some electified funky music  
Hey wait a minute  
Now first it wasn't easy changin' rock and roll and minds  
And things were gettin' shaky (yeah)  
I thought I'd have to leave it behind  
Oh but now it's so much better it's so much better  
I'm funkin' out in every way  
But I'll never lose that feelin' no I won't  
Of how I learned my lesson that day  
When they were dancin' and singin' and movin' to the groovin'  
And just when it hit me somebody turned around and shouted  
Play that funky music white boy  
Play that funky music right  
Play that funky music white boy  
Lay down the boogie and play that funky music till you die hey  
Till you die (yeah)  
Oh' till you die... yeah  
(come on) They shouted play that funky music  
Play that funky music  
(play that funky music)  
You gotta keep on playin' funky music  
(play that funky music)  
Play that funky music  
(play that funky music)  
Wanna take you higher y'all  
(play that funky music)  
White boy  
(play that funky music)  
Right yeah  
(play that funky music)  
White boy  
(play that funky music)  
Right yeah  
(play that funky music)  
White boy  
(play that funky music)  
Right yeah  
(play that funky music) Oh baby  
(play that funky music)
