# Shake-Shake-Shake

Everybody, get on the floor, let's dance  
Don't fight your feelings, give yourself a chance  
Shake shake shake, shake shake shake  
Shake your booty, shake your booty  
Oh, shake shake shake, shake shake shake  
Shake your booty, shake your booty  
You can, you can do it very well  
You're the best in the world, I can tell  
Oh, shake shake shake, shake shake shake  
Shake your booty, shake your booty  
Oh, shake shake shake, shake shake shake  
Shake your booty, shake your booty  
Shake shake, shake shake  
Shake shake, shake shake  
Shake shake shake, shake shake shake  
Shake your booty, shake your booty  
Oh, shake shake shake, shake shake shake  
Shake your booty, shake your booty  
Shake shake, shake shake, shake your booty  
Don't fight the feeling  
Shake shake, shake shake, shake your booty  
Give yourself a chance  
Shake shake, shake shake, shake your booty  
You can do it, do it  
Shake shake, shake shake, shake your booty  
Come home with momma now  
Shake shake, shake shake, shake your booty  
Shake shake, shake shake, shake your booty  
Run down to sister  
Shake shake, come on  
Shake shake, come on  
Your booty, do your duty  
Shake shake, come on  
Shake shake, come on
