# Shine

Give me a word  
Give me a sign  
Show me where to look  
Tell me what will I find  
Will I find?  
Lay me on the ground  
Fly me in the sky  
Show me where to look  
Tell me what will I find  
Will I find?  
Yea  
Yea  
Yea  
Ohh, Heaven let your light shine down  
Ohh, Heaven let your light shine down  
Ohh, Heaven let your light shine down  
Ohh, Heaven let your light shine down  
Love is in the water  
Love is in the air  
Show me where to look  
Tell me will love be there  
Will love be there?  
Teach me how to speak  
Teach me how to share  
Teach me where to go  
Tell me will love be there  
Will love be there?  
Yea  
Oh  
Yea  
Ohh, Heaven let your light shine down  
Ohh, Heaven let your light shine down  
Ohh, Heaven let your light shine down  
Ohh, Heaven let your light shine down  
Give me a word  
Give me a sign  
Show me where to look  
Tell me what will I find  
Will I find?  
Lay me on the ground  
Fly me in the sky  
Show me where to look  
Tell me what will I find  
Will I find?  
Yea  
Yea  
Yea  
Ohh, Heaven let your light shine down  
Ohh, Heaven let your light shine down  
Ohh, Heaven let your light shine down  
Ohh, Heaven let your light shine down  
I'm gonna let it shine  
I'm gonna let it shine  
Heaven's little light gonna shine on me  
Hey hey Heaven's little light gonna shine on me  
(Shine)  
Shine on me  
Hey hey yea hey hey  
(Shine)  
Come on and shine
