# Thank-You-Falettinme-Be-Mice-Elf-Agin

Sly And The Family Stone  
Miscellaneous  
Thank You (Falettinme Be Mice Elf Agin)  
Lookin' at the devil, grinnin' at his gun  
Fingers start shakin', I begin to run  
Bullets start chasin', I begin to stop  
We begin to wrestle I was on the top  
Want to thank you falettinme be mice elf agin  
I wanna thank you falettinme be mice elf agin  
Stiff all in the collar, fluffy in the face  
Chit chat chatter tryin', I begin to run  
Want to thank you for the party, I could never stay  
Many thangs is on my mind, words in the way  
Want to thank you falettinme be mice elf agin  
Thank you falettinme be mice elf agin  
Dance to the music  
All nite long  
Everyday people  
Sing a simple song  
Mama's so happy  
Mama start to cry  
Papa still singin'  
You can make it if you try  
I want to thank you falettinme be mice elf agin  
Thank you falettinme be mice elf agin  
Flamin' eyes of people fear, burnin' into you  
Many men are missin' much, hatin' what they do  
Youth and truth are makin' love  
Dig it for a starter  
Dyin' young is hard to take  
Sellin' out is harder  
I want to thank you falettinme be mice elf agin  
Thank you falettinme be mice elf agin
