# The-Big-Bang

Oh, babe  
I don't wanna lie  
I'm gonna take what you're giving  
'Cause I know you're willing  
To take me all the way  
You got me right here  
Impossible  
And I can't wait to finally explode  
The Big, Big Bang  
The reason I'm alive  
When all the stars collide  
In this universe inside  
The big, big bang  
The big, big bang  
The big, big bang  
Some people like to talk  
But I'm into doing  
What I feel like doing  
When I'm inspired to  
If we take a walk down the beach tonight  
I bet that we could light up the sky  
The Big, Big Bang  
The reason I'm alive  
When all the stars collide  
In this universe inside  
The big, big bang  
The big, big bang  
The big, big bang  
Take it for me, I don't wanna be mummified  
Sometimes I feel so isolated  
I wanna die and I'll take it from you if you got it every time  
So baby, bring your body here, next to mine  
Next to mine  
Next to mine when I don't wanna dance  
I just wanna live it  
So baby, let's not miss this thing  
The Big, Big Bang  
The reason I'm alive  
When all the stars collide  
In this universe inside  
The big, big bang  
The big, big bang  
The big, big bang
